/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EbbinghausPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/CalendarView.ts
var import_obsidian2 = require("obsidian");

// src/ebbinghaus.ts
var DEFAULT_INTERVALS = [1, 2, 4, 7, 15, 30, 60, 120];
function getReviewDates(mtime, intervals) {
  return intervals.map((days) => {
    const d = new Date(mtime);
    d.setDate(d.getDate() + days);
    d.setHours(0, 0, 0, 0);
    return d;
  });
}
function toDateKey(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function isOverdue(reviewDate, today) {
  const t = new Date(today);
  t.setHours(0, 0, 0, 0);
  return reviewDate < t;
}

// src/noteScanner.ts
function scanNotes(app, intervals, pinnedDates) {
  let newPinsAdded = false;
  const files = app.vault.getMarkdownFiles();
  const records = files.map((file) => {
    let baseTs;
    if (pinnedDates[file.path] !== void 0) {
      baseTs = pinnedDates[file.path];
    } else {
      baseTs = file.stat.mtime;
      pinnedDates[file.path] = baseTs;
      newPinsAdded = true;
    }
    const baseDate = new Date(baseTs);
    baseDate.setHours(0, 0, 0, 0);
    const reviewDates = getReviewDates(baseDate, intervals).map((date, idx) => ({
      dateKey: toDateKey(date),
      repetition: idx + 1,
      date
    }));
    return { file, baseDate, reviewDates };
  });
  return { records, newPinsAdded };
}
function buildDayMaps(records) {
  const createdMap = /* @__PURE__ */ new Map();
  const reviewMap = /* @__PURE__ */ new Map();
  for (const record of records) {
    const ck = toDateKey(record.baseDate);
    if (!createdMap.has(ck)) createdMap.set(ck, []);
    createdMap.get(ck).push(record);
    for (const rv of record.reviewDates) {
      if (!reviewMap.has(rv.dateKey)) reviewMap.set(rv.dateKey, []);
      reviewMap.get(rv.dateKey).push({
        record,
        repetition: rv.repetition
      });
    }
  }
  return { createdMap, reviewMap };
}

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  intervals: DEFAULT_INTERVALS,
  showStartupNotice: true,
  completedReviews: {},
  neverReview: {},
  pinnedDates: {}
};
function reviewKey(filePath, repetition) {
  return `${filePath}::${repetition}`;
}
var EbbinghausSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u827E\u5BBE\u6D69\u65AF\u590D\u4E60\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u590D\u4E60\u95F4\u9694\uFF08\u5929\uFF09").setDesc("\u7528\u82F1\u6587\u9017\u53F7\u5206\u9694\u7684\u5929\u6570\u5217\u8868\uFF0C\u4F8B\u5982\uFF1A1,2,4,7,15,30,60,120").addText((text) => {
      text.setPlaceholder("1,2,4,7,15,30,60,120").setValue(this.plugin.settings.intervals.join(",")).onChange(async (value) => {
        const parsed = value.split(",").map((s) => parseInt(s.trim(), 10)).filter((n) => !isNaN(n) && n > 0);
        if (parsed.length > 0) {
          this.plugin.settings.intervals = parsed;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.style.width = "300px";
    });
    new import_obsidian.Setting(containerEl).setName("\u542F\u52A8\u65F6\u663E\u793A\u4ECA\u65E5\u5F85\u590D\u4E60\u6570\u91CF").setDesc("\u6BCF\u6B21\u6253\u5F00 Obsidian \u65F6\uFF0C\u5728\u901A\u77E5\u680F\u63D0\u793A\u4ECA\u5929\u6709\u591A\u5C11\u7B14\u8BB0\u9700\u8981\u590D\u4E60\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStartupNotice).onChange(async (value) => {
        this.plugin.settings.showStartupNotice = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u91CD\u7F6E\u6240\u6709\u590D\u4E60\u8BB0\u5F55").setDesc("\u6E05\u9664\u6240\u6709\u5DF2\u5B8C\u6210\u7684\u590D\u4E60\u8BB0\u5F55\uFF0C\u7B14\u8BB0\u5C06\u91CD\u65B0\u51FA\u73B0\u5728\u65E5\u5386\u4E0A\u3002").addButton(
      (btn) => btn.setButtonText("\u91CD\u7F6E").setWarning().onClick(async () => {
        this.plugin.settings.completedReviews = {};
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u91CD\u7F6E\u6C38\u4E0D\u590D\u4E60\u540D\u5355").setDesc("\u6E05\u9664\u6240\u6709\u6807\u8BB0\u4E3A'\u6C38\u4E0D\u590D\u4E60'\u7684\u7B14\u8BB0\uFF0C\u4F7F\u5176\u91CD\u65B0\u51FA\u73B0\u5728\u65E5\u5386\u4E2D\u3002").addButton(
      (btn) => btn.setButtonText("\u91CD\u7F6E").setWarning().onClick(async () => {
        this.plugin.settings.neverReview = {};
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u5F53\u524D\u590D\u4E60\u95F4\u9694\u9884\u89C8" });
    const preview = containerEl.createEl("div", { cls: "eb-intervals-preview" });
    this.plugin.settings.intervals.forEach((days, i) => {
      preview.createEl("span", {
        cls: "eb-interval-badge",
        text: `\u7B2C${i + 1}\u6B21: +${days}\u5929`
      });
    });
  }
};

// src/tagManager.ts
async function markReviewedInFrontmatter(app, file, repetition) {
  const tagValue = `eb-reviewed-${repetition}`;
  await app.fileManager.processFrontMatter(
    file,
    (fm) => {
      let tags = fm["tags"];
      if (!tags) {
        tags = [];
      } else if (typeof tags === "string") {
        tags = [tags];
      } else if (!Array.isArray(tags)) {
        tags = [];
      }
      const arr = tags;
      if (!arr.includes(tagValue)) {
        arr.push(tagValue);
      }
      fm["tags"] = arr;
    }
  );
}

// src/CalendarView.ts
var VIEW_TYPE_CALENDAR = "ebbinghaus-calendar-view";
var WEEKDAYS_SHORT = ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
var WEEKDAY_FULL = ["\u5468\u65E5", "\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D"];
var MONTH_NAMES = [
  "\u4E00\u6708",
  "\u4E8C\u6708",
  "\u4E09\u6708",
  "\u56DB\u6708",
  "\u4E94\u6708",
  "\u516D\u6708",
  "\u4E03\u6708",
  "\u516B\u6708",
  "\u4E5D\u6708",
  "\u5341\u6708",
  "\u5341\u4E00\u6708",
  "\u5341\u4E8C\u6708"
];
function rectsIntersect(a, b) {
  return !(a.right < b.left || a.left > b.right || a.bottom < b.top || a.top > b.bottom);
}
function startOfWeek(date) {
  const d = new Date(date);
  d.setDate(d.getDate() - d.getDay());
  d.setHours(0, 0, 0, 0);
  return d;
}
function addDays(date, n) {
  const d = new Date(date);
  d.setDate(d.getDate() + n);
  return d;
}
var CalendarView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.viewMode = "month";
    this.createdMap = /* @__PURE__ */ new Map();
    this.reviewMap = /* @__PURE__ */ new Map();
    // Drag-select state
    this.selectionPopup = null;
    this.gridEl = null;
    this.plugin = plugin;
    const now = /* @__PURE__ */ new Date();
    this.currentDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }
  getViewType() {
    return VIEW_TYPE_CALENDAR;
  }
  getDisplayText() {
    return "\u827E\u5BBE\u6D69\u65AF\u590D\u4E60\u65E5\u5386";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    this.rebuildMaps();
    this.render();
    this.registerEvent(this.app.vault.on("modify", () => {
      this.rebuildMaps();
      this.render();
    }));
    this.registerEvent(this.app.vault.on("create", () => {
      this.rebuildMaps();
      this.render();
    }));
    this.registerEvent(this.app.vault.on("delete", () => {
      this.rebuildMaps();
      this.render();
    }));
    this.registerEvent(this.app.vault.on("rename", () => {
      this.rebuildMaps();
      this.render();
    }));
  }
  async onClose() {
    this.clearSelectionPopup();
  }
  rebuildMaps() {
    const { records, newPinsAdded } = scanNotes(
      this.app,
      this.plugin.settings.intervals,
      this.plugin.settings.pinnedDates
    );
    if (newPinsAdded) {
      this.plugin.saveSettings().catch(() => {
      });
    }
    const { createdMap, reviewMap } = buildDayMaps(records);
    this.createdMap = createdMap;
    this.reviewMap = reviewMap;
  }
  refresh() {
    this.rebuildMaps();
    this.render();
  }
  // ─── Navigation helpers ───────────────────────────────────────────
  navigate(dir) {
    if (this.viewMode === "day") {
      this.currentDate = addDays(this.currentDate, dir);
    } else if (this.viewMode === "week") {
      this.currentDate = addDays(this.currentDate, dir * 7);
    } else {
      const d = new Date(this.currentDate);
      d.setMonth(d.getMonth() + dir);
      this.currentDate = d;
    }
    this.render();
  }
  goToToday() {
    const now = /* @__PURE__ */ new Date();
    this.currentDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    this.render();
  }
  navLabel() {
    const d = this.currentDate;
    if (this.viewMode === "day") {
      return `${d.getFullYear()}\u5E74${d.getMonth() + 1}\u6708${d.getDate()}\u65E5 ${WEEKDAY_FULL[d.getDay()]}`;
    } else if (this.viewMode === "week") {
      const ws = startOfWeek(d);
      const we = addDays(ws, 6);
      const sameMonth = ws.getMonth() === we.getMonth();
      if (sameMonth) {
        return `${ws.getFullYear()}\u5E74${ws.getMonth() + 1}\u6708 ${ws.getDate()}\u2013${we.getDate()}\u65E5`;
      }
      return `${ws.getMonth() + 1}\u6708${ws.getDate()}\u65E5 \u2013 ${we.getMonth() + 1}\u6708${we.getDate()}\u65E5`;
    } else {
      return `${d.getFullYear()}\u5E74 ${MONTH_NAMES[d.getMonth()]}`;
    }
  }
  // ─── Main Render ──────────────────────────────────────────────────
  render() {
    this.clearSelectionPopup();
    const root = this.contentEl;
    root.empty();
    root.addClass("eb-main-root");
    this.renderHeader(root);
    if (this.viewMode === "day") {
      const container = root.createDiv({ cls: "eb-day-view" });
      this.gridEl = container;
      this.renderDayView(container);
      this.setupDragSelect(container);
    } else {
      this.renderWeekdayBar(root);
      const extraCls = this.viewMode === "week" ? "eb-cal-grid eb-cal-grid-week" : "eb-cal-grid";
      const grid = root.createDiv({ cls: extraCls });
      this.gridEl = grid;
      if (this.viewMode === "month") {
        this.renderMonthGrid(grid);
      } else {
        this.renderWeekGrid(grid);
      }
      this.setupDragSelect(grid);
    }
    this.renderLegend(root);
  }
  // ─── Header ───────────────────────────────────────────────────────
  renderHeader(parent) {
    var _a;
    const header = parent.createDiv({ cls: "eb-main-header" });
    const navLeft = header.createDiv({ cls: "eb-nav-group" });
    navLeft.createEl("button", { cls: "eb-btn eb-btn-nav", text: "\u25C0" }).addEventListener("click", () => this.navigate(-1));
    const center = header.createDiv({ cls: "eb-header-center" });
    const titleBlock = center.createDiv({ cls: "eb-header-title" });
    titleBlock.createEl("h2", { cls: "eb-header-month", text: this.navLabel() });
    const todayKey = toDateKey(/* @__PURE__ */ new Date());
    const todayReviews = (_a = this.reviewMap.get(todayKey)) != null ? _a : [];
    const pending = todayReviews.filter(
      (r) => !this.plugin.settings.completedReviews[reviewKey(r.record.file.path, r.repetition)] && !this.plugin.settings.neverReview[r.record.file.path]
    );
    if (pending.length > 0) {
      titleBlock.createEl("span", { cls: "eb-today-badge", text: `\u4ECA\u65E5\u5F85\u590D\u4E60 ${pending.length} \u7BC7` });
    }
    const toggle = center.createDiv({ cls: "eb-view-toggle" });
    ["day", "week", "month"].forEach((mode) => {
      const labels = { day: "\u65E5", week: "\u5468", month: "\u6708" };
      const btn = toggle.createEl("button", {
        cls: `eb-toggle-btn ${this.viewMode === mode ? "eb-toggle-btn-active" : ""}`,
        text: labels[mode]
      });
      btn.addEventListener("click", () => {
        this.viewMode = mode;
        this.render();
      });
    });
    const navRight = header.createDiv({ cls: "eb-nav-group" });
    navRight.createEl("button", { cls: "eb-btn eb-btn-today", text: "\u4ECA\u5929" }).addEventListener("click", () => this.goToToday());
    navRight.createEl("button", { cls: "eb-btn eb-btn-nav", text: "\u25B6" }).addEventListener("click", () => this.navigate(1));
  }
  // ─── Weekday Bar ──────────────────────────────────────────────────
  renderWeekdayBar(parent) {
    const bar = parent.createDiv({ cls: "eb-weekday-bar" });
    WEEKDAYS_SHORT.forEach((d) => bar.createDiv({ cls: "eb-weekday-label", text: `\u5468${d}` }));
  }
  // ─── Month Grid ───────────────────────────────────────────────────
  renderMonthGrid(grid) {
    var _a;
    const today = /* @__PURE__ */ new Date();
    const todayKey = toDateKey(today);
    const y = this.currentDate.getFullYear();
    const m = this.currentDate.getMonth();
    const firstDay = new Date(y, m, 1);
    const lastDay = new Date(y, m + 1, 0);
    const startOffset = firstDay.getDay();
    for (let i = 0; i < startOffset; i++) grid.createDiv({ cls: "eb-cell eb-cell-filler" });
    for (let d = 1; d <= lastDay.getDate(); d++) {
      const date = new Date(y, m, d);
      const dateKey = toDateKey(date);
      const cell = this.renderCell(grid, dateKey, d, dateKey === todayKey, today, "month");
      (_a = cell.querySelector(".eb-cell-date-num")) == null ? void 0 : _a.addEventListener("click", () => {
        this.currentDate = date;
        this.viewMode = "day";
        this.render();
      });
    }
    const total = startOffset + lastDay.getDate();
    const rem = total % 7;
    if (rem !== 0) for (let i = 0; i < 7 - rem; i++) grid.createDiv({ cls: "eb-cell eb-cell-filler" });
  }
  // ─── Week Grid ────────────────────────────────────────────────────
  renderWeekGrid(grid) {
    var _a;
    const today = /* @__PURE__ */ new Date();
    const todayKey = toDateKey(today);
    const ws = startOfWeek(this.currentDate);
    for (let i = 0; i < 7; i++) {
      const date = addDays(ws, i);
      const dateKey = toDateKey(date);
      const cell = this.renderCell(grid, dateKey, date.getDate(), dateKey === todayKey, today, "week");
      (_a = cell.querySelector(".eb-cell-date-num")) == null ? void 0 : _a.addEventListener("click", () => {
        this.currentDate = date;
        this.viewMode = "day";
        this.render();
      });
    }
  }
  // ─── Day View ────────────────────────────────────────────────────
  renderDayView(container) {
    var _a, _b;
    const today = /* @__PURE__ */ new Date();
    const dateKey = toDateKey(this.currentDate);
    const created = (_a = this.createdMap.get(dateKey)) != null ? _a : [];
    const modSection = container.createDiv({ cls: "eb-day-section" });
    modSection.createEl("h3", {
      cls: "eb-day-section-title eb-day-section-title-mod",
      text: `\u{1F4DD} \u5F53\u65E5\u4FEE\u6539\u7684\u7B14\u8BB0\uFF08${created.length}\uFF09`
    });
    if (created.length === 0) {
      modSection.createEl("p", { cls: "eb-empty-hint", text: "\u5F53\u5929\u6CA1\u6709\u4FEE\u6539\u7B14\u8BB0" });
    } else {
      created.forEach(({ file }) => {
        const item = modSection.createDiv({ cls: "eb-day-note-item eb-day-note-created" });
        item.dataset.notePath = file.path;
        item.dataset.noteType = "created";
        const link = item.createEl("a", { cls: "eb-day-note-link", text: file.basename });
        link.title = file.path;
        link.addEventListener("click", () => this.openFile(file));
        const actions = item.createDiv({ cls: "eb-day-note-actions" });
        const neverBtn = actions.createEl("button", { cls: "eb-never-btn", text: "\u2717 \u6C38\u4E0D\u590D\u4E60" });
        neverBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.neverReviewSingle(file);
        });
      });
    }
    const reviews = ((_b = this.reviewMap.get(dateKey)) != null ? _b : []).filter(
      (r) => !this.plugin.settings.completedReviews[reviewKey(r.record.file.path, r.repetition)] && !this.plugin.settings.neverReview[r.record.file.path]
    );
    const rvSection = container.createDiv({ cls: "eb-day-section" });
    rvSection.createEl("h3", {
      cls: "eb-day-section-title eb-day-section-title-review",
      text: `\u{1F514} \u5F85\u590D\u4E60\u7B14\u8BB0\uFF08${reviews.length}\uFF09`
    });
    if (reviews.length === 0) {
      rvSection.createEl("p", { cls: "eb-empty-hint", text: "\u5F53\u5929\u6CA1\u6709\u590D\u4E60\u4EFB\u52A1 \u{1F389}" });
    } else {
      reviews.forEach(({ record, repetition }) => {
        const reviewDate = record.reviewDates.find((rv) => rv.repetition === repetition).date;
        const overdue = isOverdue(reviewDate, today);
        const item = rvSection.createDiv({
          cls: `eb-day-note-item eb-day-note-review eb-rep-item-${repetition} ${overdue ? "eb-day-note-overdue" : ""}`
        });
        item.dataset.notePath = record.file.path;
        item.dataset.noteType = "review";
        item.dataset.repetition = String(repetition);
        item.createEl("span", {
          cls: `eb-rep-badge eb-rep-${repetition} ${overdue ? "eb-rep-overdue" : ""}`,
          text: `\u7B2C${repetition}\u6B21`
        });
        const link = item.createEl("a", { cls: "eb-day-note-link eb-review-link", text: record.file.basename });
        link.title = `\u70B9\u51FB\u6253\u5F00\u5E76\u5B8C\u6210\u7B2C${repetition}\u6B21\u590D\u4E60`;
        link.addEventListener("click", async (e) => {
          e.stopPropagation();
          this.openFile(record.file);
          await this.completeReview(record.file, repetition, item);
        });
        if (overdue) {
          item.createEl("span", { cls: "eb-overdue-label", text: "\u903E\u671F" });
        }
        const actions = item.createDiv({ cls: "eb-day-note-actions" });
        const doneBtn = actions.createEl("button", { cls: "eb-done-btn", text: "\u2713 \u5B8C\u6210\u590D\u4E60" });
        doneBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.completeReview(record.file, repetition, item);
        });
        const neverBtn = actions.createEl("button", { cls: "eb-never-btn", text: "\u2717 \u6C38\u4E0D\u590D\u4E60" });
        neverBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.neverReviewSingle(record.file);
        });
      });
    }
  }
  // ─── Shared Cell (Month + Week) ───────────────────────────────────
  renderCell(parent, dateKey, dayNum, isToday, today, mode) {
    var _a, _b;
    const cell = parent.createDiv({ cls: "eb-cell" });
    if (isToday) cell.addClass("eb-cell-today");
    const dateRow = cell.createDiv({ cls: "eb-cell-date-row" });
    dateRow.createDiv({
      cls: `eb-cell-date-num ${isToday ? "eb-date-today" : ""}`,
      text: String(dayNum)
    });
    const limit = mode === "week" ? 20 : 10;
    const rvLimit = mode === "week" ? 12 : 8;
    const created = (_a = this.createdMap.get(dateKey)) != null ? _a : [];
    if (created.length > 0) {
      const section = cell.createDiv({ cls: "eb-cell-section" });
      created.slice(0, limit).forEach(({ file }) => {
        const item = section.createDiv({ cls: "eb-cell-note eb-note-created" });
        item.dataset.notePath = file.path;
        item.dataset.noteType = "created";
        const link = item.createEl("a", { cls: "eb-note-name", text: file.basename });
        link.addEventListener("click", (e) => {
          e.stopPropagation();
          this.openFile(file);
        });
      });
      if (created.length > limit) {
        section.createDiv({ cls: "eb-cell-more", text: `\u8FD8\u6709 ${created.length - limit} \u6761\u2026` });
      }
    }
    const reviews = ((_b = this.reviewMap.get(dateKey)) != null ? _b : []).filter(
      (r) => !this.plugin.settings.completedReviews[reviewKey(r.record.file.path, r.repetition)] && !this.plugin.settings.neverReview[r.record.file.path]
    );
    if (reviews.length > 0) {
      if (created.length > 0) cell.createDiv({ cls: "eb-cell-divider" });
      const section = cell.createDiv({ cls: "eb-cell-section" });
      reviews.slice(0, rvLimit).forEach(({ record, repetition }) => {
        const reviewDate = record.reviewDates.find((rv) => rv.repetition === repetition).date;
        const overdue = isOverdue(reviewDate, today);
        const item = section.createDiv({
          cls: `eb-cell-note eb-note-review eb-rep-item-${repetition} ${overdue ? "eb-note-overdue" : ""}`
        });
        item.dataset.notePath = record.file.path;
        item.dataset.noteType = "review";
        item.dataset.repetition = String(repetition);
        item.createEl("span", {
          cls: `eb-rep-badge eb-rep-${repetition} ${overdue ? "eb-rep-overdue" : ""}`,
          text: `\u7B2C${repetition}\u6B21`
        });
        const link = item.createEl("a", { cls: "eb-note-name eb-review-link", text: record.file.basename });
        link.title = `\u70B9\u51FB\u6253\u5F00\u5E76\u5B8C\u6210\u7B2C${repetition}\u6B21\u590D\u4E60`;
        link.addEventListener("click", async (e) => {
          e.stopPropagation();
          this.openFile(record.file);
          await this.completeReview(record.file, repetition, item);
        });
        const doneBtn = item.createEl("button", { cls: "eb-done-btn", text: "\u2713" });
        doneBtn.title = `\u7B2C${repetition}\u6B21\u590D\u4E60\u5B8C\u6210`;
        doneBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.completeReview(record.file, repetition, item);
        });
        const neverBtn = item.createEl("button", { cls: "eb-never-btn eb-never-btn-sm", text: "\u2717" });
        neverBtn.title = "\u6C38\u4E0D\u590D\u4E60\u6B64\u7B14\u8BB0";
        neverBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.neverReviewSingle(record.file);
        });
      });
      if (reviews.length > rvLimit) {
        section.createDiv({ cls: "eb-cell-more", text: `\u8FD8\u6709 ${reviews.length - rvLimit} \u6761\u5F85\u590D\u4E60\u2026` });
      }
    }
    return cell;
  }
  // ─── Drag Select ──────────────────────────────────────────────────
  setupDragSelect(gridEl) {
    let startX = 0, startY = 0;
    let isDragging = false;
    let overlayEl = null;
    let rectEl = null;
    const updateRect = (cx, cy) => {
      if (!rectEl) return;
      rectEl.style.left = `${Math.min(cx, startX)}px`;
      rectEl.style.top = `${Math.min(cy, startY)}px`;
      rectEl.style.width = `${Math.abs(cx - startX)}px`;
      rectEl.style.height = `${Math.abs(cy - startY)}px`;
    };
    const onMouseDown = (e) => {
      if (e.button !== 0) return;
      const target = e.target;
      if (target.closest("button, a")) return;
      isDragging = true;
      startX = e.clientX;
      startY = e.clientY;
      this.clearSelectionPopup();
      this.clearNoteHighlights(gridEl);
      overlayEl = document.body.createDiv({ cls: "eb-drag-overlay" });
      rectEl = document.body.createDiv({ cls: "eb-select-rect" });
      updateRect(e.clientX, e.clientY);
      const onMove = (me) => {
        if (isDragging) updateRect(me.clientX, me.clientY);
      };
      const onUp = (me) => {
        if (!isDragging) return;
        isDragging = false;
        const selRect = rectEl.getBoundingClientRect();
        overlayEl.remove();
        rectEl.remove();
        overlayEl = null;
        rectEl = null;
        if (selRect.width < 5 && selRect.height < 5) return;
        const noteEls = gridEl.querySelectorAll(".eb-cell-note[data-note-path], .eb-day-note-item[data-note-path]");
        const selected = [];
        noteEls.forEach((el) => {
          if (rectsIntersect(selRect, el.getBoundingClientRect())) {
            el.classList.add("eb-note-selected");
            const { notePath, noteType, repetition } = el.dataset;
            if (notePath) {
              selected.push({
                path: notePath,
                type: noteType != null ? noteType : "created",
                repetition: repetition ? parseInt(repetition) : void 0
              });
            }
          }
        });
        if (selected.length > 0) {
          this.showSelectionPopup(me.clientX, me.clientY, selected, gridEl);
        }
      };
      overlayEl.addEventListener("mousemove", onMove);
      overlayEl.addEventListener("mouseup", onUp);
      e.preventDefault();
    };
    gridEl.addEventListener("mousedown", onMouseDown);
    this.register(() => gridEl.removeEventListener("mousedown", onMouseDown));
  }
  // ─── Selection Popup ──────────────────────────────────────────────
  showSelectionPopup(clientX, clientY, selected, gridEl) {
    this.clearSelectionPopup();
    const popup = document.body.createDiv({ cls: "eb-selection-popup" });
    this.selectionPopup = popup;
    const popupW = 260, popupH = 110;
    popup.style.left = `${Math.max(8, Math.min(clientX + 12, window.innerWidth - popupW - 8))}px`;
    popup.style.top = `${Math.max(8, Math.min(clientY - 12, window.innerHeight - popupH - 8))}px`;
    const reviewItems = selected.filter((s) => s.type === "review");
    popup.createEl("p", {
      cls: "eb-popup-count",
      text: `\u5DF2\u9009\u4E2D ${selected.length} \u6761\u7B14\u8BB0${reviewItems.length > 0 ? `\uFF08\u542B ${reviewItems.length} \u6761\u590D\u4E60\uFF09` : ""}`
    });
    const btnRow = popup.createDiv({ cls: "eb-popup-btn-row" });
    if (reviewItems.length > 0) {
      btnRow.createEl("button", { cls: "eb-popup-btn eb-popup-btn-done", text: "\u2713 \u5B8C\u6210\u590D\u4E60" }).addEventListener("click", async () => {
        this.clearSelectionPopup();
        this.clearNoteHighlights(gridEl);
        await this.completeSelectedReviews(reviewItems);
      });
    }
    btnRow.createEl("button", { cls: "eb-popup-btn eb-popup-btn-never", text: "\u2717 \u6C38\u4E0D\u590D\u4E60" }).addEventListener("click", async () => {
      this.clearSelectionPopup();
      this.clearNoteHighlights(gridEl);
      await this.neverReviewSelected(selected);
    });
    const closeOn = (e) => {
      if (!popup.contains(e.target)) {
        this.clearSelectionPopup();
        this.clearNoteHighlights(gridEl);
        document.removeEventListener("mousedown", closeOn);
      }
    };
    setTimeout(() => document.addEventListener("mousedown", closeOn), 0);
  }
  clearSelectionPopup() {
    var _a;
    (_a = this.selectionPopup) == null ? void 0 : _a.remove();
    this.selectionPopup = null;
  }
  clearNoteHighlights(gridEl) {
    gridEl.querySelectorAll(".eb-note-selected").forEach((el) => el.classList.remove("eb-note-selected"));
  }
  // ─── Actions ──────────────────────────────────────────────────────
  async completeReview(file, repetition, itemEl) {
    itemEl.addClass("eb-done-animate");
    this.plugin.settings.completedReviews[reviewKey(file.path, repetition)] = true;
    await this.plugin.saveSettings();
    try {
      await markReviewedInFrontmatter(this.app, file, repetition);
      new import_obsidian2.Notice(`\u2705 \u300A${file.basename}\u300B\u7B2C${repetition}\u6B21\u590D\u4E60\u5B8C\u6210\uFF01\u5DF2\u6DFB\u52A0\u6807\u7B7E #eb-reviewed-${repetition}`);
    } catch (e) {
      new import_obsidian2.Notice(`\u26A0\uFE0F \u590D\u4E60\u5DF2\u8BB0\u5F55\uFF0C\u4F46\u5199\u5165\u6807\u7B7E\u5931\u8D25\uFF1A${e}`);
    }
    setTimeout(() => this.render(), 350);
  }
  async completeSelectedReviews(items) {
    let count = 0;
    for (const item of items) {
      if (item.type !== "review" || item.repetition == null) continue;
      const file = this.app.vault.getFileByPath(item.path);
      if (!file) continue;
      this.plugin.settings.completedReviews[reviewKey(item.path, item.repetition)] = true;
      count++;
      try {
        await markReviewedInFrontmatter(this.app, file, item.repetition);
      } catch (e) {
      }
    }
    await this.plugin.saveSettings();
    new import_obsidian2.Notice(`\u2705 \u5DF2\u5B8C\u6210 ${count} \u6761\u7B14\u8BB0\u7684\u590D\u4E60\uFF0C\u5E76\u5199\u5165\u6807\u7B7E\u3002`);
    this.render();
  }
  async neverReviewSingle(file) {
    this.plugin.settings.neverReview[file.path] = true;
    await this.plugin.saveSettings();
    new import_obsidian2.Notice(`\u{1F6AB} \u300A${file.basename}\u300B\u5DF2\u6807\u8BB0\u4E3A"\u6C38\u4E0D\u590D\u4E60"\u3002`);
    this.render();
  }
  async neverReviewSelected(items) {
    const paths = [...new Set(items.map((i) => i.path))];
    for (const p of paths) this.plugin.settings.neverReview[p] = true;
    await this.plugin.saveSettings();
    new import_obsidian2.Notice(`\u{1F6AB} \u5DF2\u5C06 ${paths.length} \u6761\u7B14\u8BB0\u6807\u8BB0\u4E3A"\u6C38\u4E0D\u590D\u4E60"\u3002`);
    this.render();
  }
  // ─── Legend ───────────────────────────────────────────────────────
  renderLegend(parent) {
    const legend = parent.createDiv({ cls: "eb-legend-bar" });
    const mk = (cls, label) => {
      const item = legend.createDiv({ cls: "eb-legend-item" });
      item.createDiv({ cls });
      item.createEl("span", { text: label });
    };
    mk("eb-dot-created-sm", "\u5F53\u5929\u5EFA\u7ACB");
    mk("eb-dot-review-sm", "\u5F85\u590D\u4E60");
    mk("eb-dot-overdue-sm", "\u5DF2\u903E\u671F");
    legend.createEl("span", { cls: "eb-legend-hint", text: "\u{1F4A1} \u62D6\u52A8\u6846\u9009\u7B14\u8BB0\u53EF\u6279\u91CF\u64CD\u4F5C | \u70B9\u51FB\u65E5\u671F\u6570\u5B57\u5207\u6362\u5230\u65E5\u89C6\u56FE" });
  }
  openFile(file) {
    this.app.workspace.getLeaf("tab").openFile(file);
  }
};

// src/main.ts
var EbbinghausPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    /** Track which MarkdownView instances already have our action button */
    this.buttonizedViews = /* @__PURE__ */ new WeakSet();
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_CALENDAR, (leaf) => new CalendarView(leaf, this));
    this.addRibbonIcon("brain", "\u6253\u5F00\u827E\u5BBE\u6D69\u65AF\u590D\u4E60\u65E5\u5386", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-review-calendar",
      name: "\u6253\u5F00\u590D\u4E60\u65E5\u5386",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "reset-review-date",
      name: "\u91CD\u65B0\u89C4\u5212\u5F53\u524D\u7B14\u8BB0\u7684\u590D\u4E60\u8BA1\u5212\uFF08\u4ECE\u4ECA\u5929\u5F00\u59CB\uFF09",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (view == null ? void 0 : view.file) {
          if (!checking) this.resetReviewDate(view.file);
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new EbbinghausSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.addReviewButtonsToAllLeaves();
      if (this.settings.showStartupNotice) this.showTodayNotice();
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.addReviewButtonsToAllLeaves();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.addReviewButtonsToAllLeaves();
      })
    );
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CALENDAR);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!this.settings.completedReviews) this.settings.completedReviews = {};
    if (!this.settings.neverReview) this.settings.neverReview = {};
    if (!this.settings.pinnedDates) this.settings.pinnedDates = {};
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.getLeavesOfType(VIEW_TYPE_CALENDAR).forEach((leaf) => {
      leaf.view.refresh();
    });
  }
  /** Open calendar as a main-area tab */
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_CALENDAR);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_CALENDAR, active: true });
    workspace.revealLeaf(leaf);
  }
  // ─── Add action button to all MarkdownView instances ─────────────
  addReviewButtonsToAllLeaves() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView && !this.buttonizedViews.has(view)) {
        this.buttonizedViews.add(view);
        view.addAction(
          "refresh-cw",
          "\u91CD\u7F6E\u590D\u4E60\u8BA1\u5212\uFF08\u4ECE\u4ECA\u5929\u91CD\u65B0\u5F00\u59CB\uFF09",
          () => {
            if (view.file) this.resetReviewDate(view.file);
          }
        );
      }
    });
  }
  // ─── Reset review date for a note ────────────────────────────────
  async resetReviewDate(file) {
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const todayStr = toDateKey(today);
    this.settings.pinnedDates[file.path] = today.getTime();
    const keysToDelete = Object.keys(this.settings.completedReviews).filter(
      (k) => k.startsWith(file.path + "::")
    );
    keysToDelete.forEach((k) => delete this.settings.completedReviews[k]);
    await this.saveSettings();
    new import_obsidian3.Notice(
      `\u{1F4C5} \u300A${file.basename}\u300B\u7684\u590D\u4E60\u8BA1\u5212\u5DF2\u91CD\u7F6E\uFF01
\u4ECE\u4ECA\u5929 (${todayStr}) \u8D77\u6309\u827E\u5BBE\u6D69\u65AF\u66F2\u7EBF\u91CD\u65B0\u63D0\u9192\u3002`,
      6e3
    );
  }
  // ─── Startup notice ───────────────────────────────────────────────
  showTodayNotice() {
    const todayKey = toDateKey(/* @__PURE__ */ new Date());
    const { records } = scanNotes(this.app, this.settings.intervals, this.settings.pinnedDates);
    let count = 0;
    for (const record of records) {
      for (const rv of record.reviewDates) {
        if (rv.dateKey === todayKey) {
          const key = reviewKey(record.file.path, rv.repetition);
          if (!this.settings.completedReviews[key] && !this.settings.neverReview[record.file.path]) {
            count++;
          }
        }
      }
    }
    if (count > 0) {
      new import_obsidian3.Notice(`\u{1F4C5} \u4ECA\u5929\u6709 ${count} \u6761\u7B14\u8BB0\u9700\u8981\u6839\u636E\u827E\u5BBE\u6D69\u65AF\u66F2\u7EBF\u590D\u4E60\uFF01`, 6e3);
    }
  }
};
